export enum TIMEZONE {
  NEW_YORK = 'America/New_York',
  CHICAGO = 'America/Chicago',
  DENVER = 'America/Denver',
  LOS_ANGELES = 'America/Los_Angeles',
  GMT = 'GMT',
  PARIS = 'Europe/Paris',
  ATHENS = 'Europe/Athens',
  LONDON = 'Europe/London',
  KOLKATA = 'Asia/Kolkata',
  TOKYO = 'Asia/Tokyo',
  ADELAIDE = 'Australia/Adelaide',
  SAO_PAULO = 'America/Sao_Paulo',
  BUENOS_AIRES = 'America/Argentina/Buenos_Aires',
}
